AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'test/dummy/**/*'
    - 'sse_rails_engine.gemspec'
    - 'db/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/FileName:
  Enabled: false

Style/GuardClause:
  Enabled: false
