language: ruby

cache:
  bundler: true

rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1

sudo: false

before_install:
  - gem install bundler

script:
  - bundle exec rake test

matrix:
  include:
    - rvm: 2.3.7
      script: bundle exec rubocop
